In [91]:
# specify a hypergraph via matrix
edgeList = Matrix([
        (1,1,0,0,1,0,0,1,2,0,0),
        (1,1,1,0,0,0,1,0,0,2,0),
        (1,0,1,1,1,0,0,0,0,0,2),
        (0,0,1,1,0,1,1,0,2,0,0),
        (0,0,0,1,1,1,0,1,0,2,0),
        (0,1,0,0,0,1,1,1,0,0,2)
    ])

       1  (1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0)
       2  (1,1,1,1,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0)
       3  (1,0,0,0,1,1,1,0,0,0,0,0,1,1,1,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,2,0)
       4  (0,1,0,0,1,0,0,1,1,0,0,0,1,0,0,1,1,0,0,0,1,1,0,0,0,1,1,1,0,0,0,0,0,0,0,2)
       -1 (0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,1,0,1,0,1,1,0,1,1,0,1,1,1,0,2,0,0,0)
       -2 (0,0,0,0,0,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,1,1,0,1,1,0,1,1,1,0,1,0,2,0,0)
       -3 (0,0,1,0,0,0,0,0,1,1,0,1,0,0,0,0,1,1,0,1,0,0,0,0,0,0,1,1,1,0,1,1,0,0,2,0)
       -4 (0,0,0,1,0,0,1,0,0,0,1,1,0,0,1,0,0,0,1,1,0,0,0,1,1,0,0,0,0,1,1,1,0,0,0,2)
        
        
       1  (1,1,1,1,1,1,0,0,0,0,0,0,0,0,2,0,0,0)
       2  (1,1,1,0,0,0,1,1,1,1,0,0,0,0,0,2,0,0)
       3  (1,1,0,1,0,0,1,1,0,0,1,1,0,0,0,0,2,0)
       4  (1,0,1,1,1,0,1,0,1,0,1,0,1,0,0,0,0,2)
       -1 (0,0,0,0,0,0,1,1,1,1,1,1,1,1,2,0,0,0)
       -2 (0,0,0,1,1,1,0,0,0,0,1,1,1,1,0,2,0,0)
       -3 (0,0,1,0,1,1,0,0,1,1,0,0,1,1,0,0,2,0)
       -4 (0,1,0,0,0,1,0,1,0,1,0,1,0,1,0,0,0,2)

IndentationError: unexpected indent (<ipython-input-91-5fb04ad22a4d>, line 11)

In [92]:
# 8verticies edgesets of 4
edgeList= Matrix([
    (1,1,1,1,1,1,0,0,0,0,0,0,0,0,2,0,0,0),
    (1,1,1,0,0,0,1,1,1,1,0,0,0,0,0,2,0,0),
    (1,1,0,1,0,0,1,1,0,0,1,1,0,0,0,0,2,0),
    (1,0,1,1,1,0,1,0,1,0,1,0,1,0,0,0,0,2),
    (0,0,0,0,0,0,1,1,1,1,1,1,1,1,2,0,0,0),
    (0,0,0,1,1,1,0,0,0,0,1,1,1,1,0,2,0,0),
    (0,0,1,0,1,1,0,0,1,1,0,0,1,1,0,0,2,0),
    (0,1,0,0,0,1,0,1,0,1,0,1,0,1,0,0,0,2)
])

In [93]:
# 8 verticies edgeset of 3
edgeList = Matrix([
        (1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0),
        (1,1,1,1,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0),
        (1,0,0,0,1,1,1,0,0,0,0,0,1,1,1,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,2,0),
        (0,1,0,0,1,0,0,1,1,0,0,0,1,0,0,1,1,0,0,0,1,1,0,0,0,1,1,1,0,0,0,0,0,0,0,2),
        (0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,1,0,1,0,1,1,0,1,1,0,1,1,1,0,2,0,0,0),
        (0,0,0,0,0,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,1,1,0,1,1,0,1,1,1,0,1,0,2,0,0),
        (0,0,1,0,0,0,0,0,1,1,0,1,0,0,0,0,1,1,0,1,0,0,0,0,0,0,1,1,1,0,1,1,0,0,2,0),
        (0,0,0,1,0,0,1,0,0,0,1,1,0,0,1,0,0,0,1,1,0,0,0,1,1,0,0,0,0,1,1,1,0,0,0,2)
    ])

In [94]:
# giant matrix from Jacob
edgeList = Matrix([
(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
   1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0),
  (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
   1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0),
  (1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 
   0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0),
  (1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 
   1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 
   0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 
   1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0),
  (0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 
   0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 
   0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 
   0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2),
  (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 
   1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 
   0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 2, 0, 0, 0, 0),
  (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 
   1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 
   1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 2, 0, 0, 0),
  (0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
   1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 
   1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 
   1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 0, 0),
  (0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 
   0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 
   1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 
   0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 2, 0),
  (0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 
   0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 
   0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 
   1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 2),
])

In [3]:
def generate_one_vertex_deleted(edgeList):
    # generate all one-vertex deleted matrices
    matrixList = []
    for i in range(len(edgeList.rows())):
        matrixList.append(edgeList.delete_rows([i]))
#         print(edgeList.delete_rows([i]))
#         print("--------------------------")
    return matrixList

In [4]:
def generate_one_vertex_deleted(edgeList):
    # generate all one-vertex deleted matrices
    matrixList = []
    for i in range(len(edgeList.rows())):
        matrixList.append(edgeList.delete_rows([i]))
#         print(edgeList.delete_rows([i]))
#         print("--------------------------")
    return matrixList


def test_isomorphism_one_vertex_deleted(matrixList):
    
    # test each one-vertex deleted matrix to each other for isomorphism
    nonIsomorphic = []
    isomorphic = []
    for i in range(len(matrixList)):
        for j in range(i+1, len(matrixList)):
    #         print(i,j)
    #         print(BipartiteGraph(matrixList[i]).is_isomorphic(BipartiteGraph(matrixList[j])))
            if BipartiteGraph(matrixList[i]).is_isomorphic(BipartiteGraph(matrixList[j])):
                isomorphic.append(str(i) + " and " + str(j))
        #             print(matrixList[i])
        #             print('h' + str(i) + ' is different from h' + str(j))
    #             print('h' + str(i) + ' is isomorphic to h' + str(j))
        #             print(matrixList[j])
        #             print('---')
            else:
                nonIsomorphic.append(str(i) + " and " + str(j))
    print("Isomorphic:", isomorphic)
    print("Non-isomorphic:", nonIsomorphic)


In [98]:
edgeNumber = 3
literalNumber = 3
vertexNumer = literalNumber * 2

def generate_red_edges(litNumber):
    '''Generate red edges of size litNumber'''
    i1 = identity_matrix(litNumber)
    i2 = identity_matrix(litNumber)
    for i in i1.rows():
        i2 = i2.insert_row(len(i2.rows()), i)
    i2 = i2 * 2
    return i2

def combine_columns(matrix1, matrix2):
    '''Add the columns from matrix2 to matrix1'''
    matrix1 = matrix1.transpose()
    for i in matrix2.columns():
        matrix1 = matrix1.insert_row(len(matrix1.rows()), i)
    matrix1 = matrix1.transpose()
    return matrix1



In [118]:
x = Matrix([
        (1,1,0,0,1,0,0,1,2,0,0),
        (1,1,1,0,0,0,1,0,0,2,0),
        (1,0,1,1,1,0,0,0,0,0,2),
        (0,0,1,1,0,1,1,0,2,0,0),
        (0,0,0,1,1,1,0,1,0,2,0),
        (0,1,0,0,0,1,1,1,0,0,2)
    ])

In [124]:
sage.combinat.combination.Combinations([1,2])

Combinations of [1, 2]

In [154]:
x1 = Matrix([
        (1,0,0,0,0,0),
        (0,0,0,0,0,0)
    ])

In [155]:
x1 = x1.transpose()

In [156]:
cartesian_product(x1,)

((1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0))

In [190]:
ro = [(i,j) for i in range(2) for j in range(2)]
print(ro)

[(0, 0), (0, 1), (1, 0), (1, 1)]


In [216]:
from itertools import product
for k in range(2, 6):
    print
    for matrices in (product(range(2), repeat=k)):
        print(matrices)


(0, 0)
(0, 1)
(1, 0)
(1, 1)

(0, 0, 0)
(0, 0, 1)
(0, 1, 0)
(0, 1, 1)
(1, 0, 0)
(1, 0, 1)
(1, 1, 0)
(1, 1, 1)

(0, 0, 0, 0)
(0, 0, 0, 1)
(0, 0, 1, 0)
(0, 0, 1, 1)
(0, 1, 0, 0)
(0, 1, 0, 1)
(0, 1, 1, 0)
(0, 1, 1, 1)
(1, 0, 0, 0)
(1, 0, 0, 1)
(1, 0, 1, 0)
(1, 0, 1, 1)
(1, 1, 0, 0)
(1, 1, 0, 1)
(1, 1, 1, 0)
(1, 1, 1, 1)

(0, 0, 0, 0, 0)
(0, 0, 0, 0, 1)
(0, 0, 0, 1, 0)
(0, 0, 0, 1, 1)
(0, 0, 1, 0, 0)
(0, 0, 1, 0, 1)
(0, 0, 1, 1, 0)
(0, 0, 1, 1, 1)
(0, 1, 0, 0, 0)
(0, 1, 0, 0, 1)
(0, 1, 0, 1, 0)
(0, 1, 0, 1, 1)
(0, 1, 1, 0, 0)
(0, 1, 1, 0, 1)
(0, 1, 1, 1, 0)
(0, 1, 1, 1, 1)
(1, 0, 0, 0, 0)
(1, 0, 0, 0, 1)
(1, 0, 0, 1, 0)
(1, 0, 0, 1, 1)
(1, 0, 1, 0, 0)
(1, 0, 1, 0, 1)
(1, 0, 1, 1, 0)
(1, 0, 1, 1, 1)
(1, 1, 0, 0, 0)
(1, 1, 0, 0, 1)
(1, 1, 0, 1, 0)
(1, 1, 0, 1, 1)
(1, 1, 1, 0, 0)
(1, 1, 1, 0, 1)
(1, 1, 1, 1, 0)
(1, 1, 1, 1, 1)


In [189]:
from itertools import permutations

In [203]:
import numpy as np
from itertools import combinations

triangle = [(i,j) for i in range(4) for j in range (i+1,4)]

def matrices():
    for t in combinations(triangle,3):
        m = np.zeros((4,4))
        for c in t:
            m[c]=1
        yield m+m.transpose()

M = [m for m in matrices()]
# print(M[-1]) # print the last matrix in the list
# print(M[0])  # print the first matrix in the list
# print(M[-1][-1,:]) #print the last row of the last matrix     
for m in matrices():
    print(m)

[[ 0.  1.  1.  1.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]]
[[ 0.  1.  1.  0.]
 [ 1.  0.  1.  0.]
 [ 1.  1.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0.  1.  1.  0.]
 [ 1.  0.  0.  1.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]]
[[ 0.  1.  1.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  1.]
 [ 0.  0.  1.  0.]]
[[ 0.  1.  0.  1.]
 [ 1.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]]
[[ 0.  1.  0.  1.]
 [ 1.  0.  0.  1.]
 [ 0.  0.  0.  0.]
 [ 1.  1.  0.  0.]]
[[ 0.  1.  0.  1.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 1.  0.  1.  0.]]
[[ 0.  1.  0.  0.]
 [ 1.  0.  1.  1.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]]
[[ 0.  1.  0.  0.]
 [ 1.  0.  1.  0.]
 [ 0.  1.  0.  1.]
 [ 0.  0.  1.  0.]]
[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 0.  1.  1.  0.]]
[[ 0.  0.  1.  1.]
 [ 0.  0.  1.  0.]
 [ 1.  1.  0.  0.]
 [ 1.  0.  0.  0.]]
[[ 0.  0.  1.  1.]
 [ 0.  0.  0.  1.]
 [ 1.  0.  0.  0.]
 [ 1.  1.  0.  0.]]
[[ 0.  0.  1.  1.]
 [ 0.  0.  0.  0.]
 [ 1.  0.  0.  1.]
 [ 1.  0.  1.  0.]]

In [159]:
triangle

[(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]

In [47]:
m = Matrix.column([(1),(0),(0),(0),(0),(0),])

In [43]:
m.permute_rows(g)

AttributeError: 'PermutationGroup_generic_with_category' object has no attribute 'cycle_tuples'

In [48]:
cartesian_product(m)

((1), (0), (0), (0), (0), (0))

In [74]:
from itertools import permutations 
permutations()

TypeError: Required argument 'iterable' (pos 1) not found

In [1]:
from itertools import permutations
def generate_edges(n, sz):
    ones = [1 for i in range(n)]  # generate a list of 1s
    zeros = [0 for i in range(sz - n)]  # generate a list of 0s
    ones.extend(zeros)  # append the 0s to the 1s
    return(set((permutations(ones))))  # return the permutations of the 1s and 0s

In [7]:
for i in range(1,4):
    print(generate_edges(i, 6))

set([(1, 0, 0, 0, 0, 0), (0, 0, 1, 0, 0, 0), (0, 1, 0, 0, 0, 0), (0, 0, 0, 1, 0, 0), (0, 0, 0, 0, 0, 1), (0, 0, 0, 0, 1, 0)])
set([(1, 0, 1, 0, 0, 0), (1, 0, 0, 0, 1, 0), (0, 0, 1, 0, 1, 0), (0, 1, 1, 0, 0, 0), (0, 1, 0, 0, 1, 0), (0, 0, 1, 1, 0, 0), (0, 0, 0, 1, 1, 0), (1, 0, 0, 0, 0, 1), (0, 0, 0, 0, 1, 1), (0, 0, 1, 0, 0, 1), (1, 0, 0, 1, 0, 0), (0, 1, 0, 0, 0, 1), (0, 1, 0, 1, 0, 0), (1, 1, 0, 0, 0, 0), (0, 0, 0, 1, 0, 1)])
set([(0, 1, 1, 0, 0, 1), (0, 1, 0, 1, 1, 0), (1, 1, 0, 0, 1, 0), (1, 0, 1, 1, 0, 0), (1, 1, 1, 0, 0, 0), (1, 0, 1, 0, 1, 0), (1, 0, 0, 0, 1, 1), (0, 0, 0, 1, 1, 1), (0, 1, 0, 0, 1, 1), (1, 0, 0, 1, 0, 1), (0, 0, 1, 1, 0, 1), (1, 1, 0, 1, 0, 0), (0, 0, 1, 1, 1, 0), (0, 1, 0, 1, 0, 1), (0, 1, 1, 0, 1, 0), (1, 1, 0, 0, 0, 1), (0, 0, 1, 0, 1, 1), (1, 0, 1, 0, 0, 1), (1, 0, 0, 1, 1, 0), (0, 1, 1, 1, 0, 0)])


In [8]:
x = []
for i in range(3):
    x.extend(generate_edges(i+1,6))

In [9]:
x

[(1, 0, 0, 0, 0, 0),
 (0, 0, 1, 0, 0, 0),
 (0, 1, 0, 0, 0, 0),
 (0, 0, 0, 1, 0, 0),
 (0, 0, 0, 0, 0, 1),
 (0, 0, 0, 0, 1, 0),
 (1, 0, 1, 0, 0, 0),
 (1, 0, 0, 0, 1, 0),
 (0, 0, 1, 0, 1, 0),
 (0, 1, 1, 0, 0, 0),
 (0, 1, 0, 0, 1, 0),
 (0, 0, 1, 1, 0, 0),
 (0, 0, 0, 1, 1, 0),
 (1, 0, 0, 0, 0, 1),
 (0, 0, 0, 0, 1, 1),
 (0, 0, 1, 0, 0, 1),
 (1, 0, 0, 1, 0, 0),
 (0, 1, 0, 0, 0, 1),
 (0, 1, 0, 1, 0, 0),
 (1, 1, 0, 0, 0, 0),
 (0, 0, 0, 1, 0, 1),
 (0, 1, 1, 0, 0, 1),
 (0, 1, 0, 1, 1, 0),
 (1, 1, 0, 0, 1, 0),
 (1, 0, 1, 1, 0, 0),
 (1, 1, 1, 0, 0, 0),
 (1, 0, 1, 0, 1, 0),
 (1, 0, 0, 0, 1, 1),
 (0, 0, 0, 1, 1, 1),
 (0, 1, 0, 0, 1, 1),
 (1, 0, 0, 1, 0, 1),
 (0, 0, 1, 1, 0, 1),
 (1, 1, 0, 1, 0, 0),
 (0, 0, 1, 1, 1, 0),
 (0, 1, 0, 1, 0, 1),
 (0, 1, 1, 0, 1, 0),
 (1, 1, 0, 0, 0, 1),
 (0, 0, 1, 0, 1, 1),
 (1, 0, 1, 0, 0, 1),
 (1, 0, 0, 1, 1, 0),
 (0, 1, 1, 1, 0, 0)]

In [86]:
for i in x:
    for e in i:
        

(1, 0, 0, 0, 0, 0)
(0, 0, 1, 0, 0, 0)
(0, 1, 0, 0, 0, 0)
(0, 0, 0, 1, 0, 0)
(0, 0, 0, 0, 0, 1)
(0, 0, 0, 0, 1, 0)
(1, 0, 1, 0, 0, 0)
(1, 0, 0, 0, 1, 0)
(0, 0, 1, 0, 1, 0)
(0, 1, 1, 0, 0, 0)
(0, 1, 0, 0, 1, 0)
(0, 0, 1, 1, 0, 0)
(0, 0, 0, 1, 1, 0)
(1, 0, 0, 0, 0, 1)
(0, 0, 0, 0, 1, 1)
(0, 0, 1, 0, 0, 1)
(1, 0, 0, 1, 0, 0)
(0, 1, 0, 0, 0, 1)
(0, 1, 0, 1, 0, 0)
(1, 1, 0, 0, 0, 0)
(0, 0, 0, 1, 0, 1)
(0, 1, 1, 0, 0, 1)
(0, 1, 0, 1, 1, 0)
(1, 1, 0, 0, 1, 0)
(1, 0, 1, 1, 0, 0)
(1, 1, 1, 0, 0, 0)
(1, 0, 1, 0, 1, 0)
(1, 0, 0, 0, 1, 1)
(0, 0, 0, 1, 1, 1)
(0, 1, 0, 0, 1, 1)
(1, 0, 0, 1, 0, 1)
(0, 0, 1, 1, 0, 1)
(1, 1, 0, 1, 0, 0)
(0, 0, 1, 1, 1, 0)
(0, 1, 0, 1, 0, 1)
(0, 1, 1, 0, 1, 0)
(1, 1, 0, 0, 0, 1)
(0, 0, 1, 0, 1, 1)
(1, 0, 1, 0, 0, 1)
(1, 0, 0, 1, 1, 0)
(0, 1, 1, 1, 0, 0)


In [17]:
ones = [1 for i in range(3)]
print(ones)

[1, 1, 1]


In [20]:
zeros = [0 for i in range( - n)]
print(zeros)

NameError: name 'sz' is not defined